### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by michaelmoussa** [zendframework/zend-expressive-router#20]
"To do" list for 2.0.0 release.
- [x] Remove `RouteResultObserverInterface` and `RouteResultSubjectInterface`
- [x] Update Travis to enforce 100% code coverage
- [x] Address "How to get defined path?" (#12)
~Update any pertinent docs, if needed~
- [x] Update branch-alias entries
- [x] Update --dev dependencies

**Comment by weierophinney** [comment]
We also now need a patch to remove the `RouteResult::fromRouteMatch()` method, as that's being marked deprecated with 1.3.0.

**Comment by michaelmoussa** [comment]
I struck out updating docs because they're not stored in this repository. Docs will be updated in applicable repositories once they release an update that pins to the new major version of `zend-expressive-router` in their respective `composer.json` files.

**Comment by michaelmoussa** [comment]
[2.0.0](https://github.com/zendframework/zend-expressive-router/releases/tag/2.0.0) has been released.
