### ISSUE TITLE
missed a PathBasedRoutingMiddleware renaming...

### ISSUE THREAD

**Issue by basz** [zendframework/zend-expressive-router#68]
- [x] I was not able to find an issue matching what I'm seeing.
 - [x] This is not a question.

This hasn't been renamed: https://github.com/zendframework/zend-expressive-router/blob/master/src/RouteCollectorFactory.php#L33 should be RouteCollector I believe

**Comment by xtreamwayz** [comment]
Yes you are right. Can you create a PR for this please? If not I can do it Monday.
