### ISSUE TITLE
problem when generating Url 

### ISSUE THREAD

**Issue by jkhaled** [zendframework/zend-expressive-router#9]
I am using fastrouter as router
I have this config
```php
[
            'name' => 'blog.post.detail',
            'path' => '/blog/post/details/{postId}[/{title}]',
            'middleware' => \Blog\Action\PostSingleAction::class,
            'allowed_methods' => ['GET'],
 ],
```
when i genrate url from view  with ```$this->url('blog.post.detail', ['postId'=>1, "title"=>"sometitle"])```
it returns
 *web.com/blog/post/details/1[/sometitle]*

**Comment by xtreamwayz** [comment]
This can be closed as it is fixed with zendframework/zend-expressive-fastroute#4.
